PennController.DebugOff()

var sendingResultsMessage = "Los resultados se están enviando al servidor.";
var completionMessage = "Los resultados se han enviado al servidor. ¡Muchas gracias!";
var progressBarText = "Barra de progreso";
var pageTitle = "Experimento";

var shuffleSequence = seq("setcounter", "intro", "demographic", "instructions", "beginning_of_practice",
							sepWith("sep", randomize("practice")),
							"end_of_practice", 
							sepWith("sep",
							shuffle(randomize(anyOf("subj-subj", "subj-indi", "indi-indi", "indi-subj",
							"first-second", "second-second", "second-first", "first-first", "filler_gr", "filler_ug")))),
							"sr", "participant_observations");

var practiceItemTypes = ["practice"];

var manualSendResults = true;

var defaults = [
    "Separator", {
        transfer: "keypress",
        normalMessage: "Pulsa la barra espaciadora para continuar.",
        errorMessage: "Error. Pulsa la barra espaciadora para continuar.",
        ignoreFailure: false
    },
    "DashedSentence", {
        hideProgressBar: true,
        mode: "self-paced reading"
    },


    "Question", {
        hideProgressBar: true,
        presentHorizontally: true,
		hasCorrect: true,
		randomOrder: false,
        as: [["s","SÍ"], ["n","NO"]]
    },
    "Message", {
        hideProgressBar: true,
        transfer: "keypress"
    },
    "Form", {
        hideProgressBar: true,
        continueOnReturn: true,
        saveReactionTime: false,
		continueMessage: "Haz clic aquí para continuar"
    }
];

var items = [



["sr", "__SendResults__", {}], 
["setcounter", "__SetCounter__", { }],


["sep", "Separator", { transfer: "keypress" }],
["intro", "Form", { html: { include: "intro.html" }}],
["demographic", "Form", { html: { include: "demographic.html" }, validators: {
        edad: function (s) { if (s.match(/^\d+$/)) return true; else return "Valor erróneo para \u2018edad\u2019"; }
        }
		}],
["instructions", "Message",{html: {include: "instructions.html"}}],

["beginning_of_practice", "Message", {html: {include: "beginning_of_practice.html"}}], 

["practice", "DashedSentence", {s:"El famoso arquitecto diseñaron el bloque de pisos más alto de la ciudad."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],
["practice", "DashedSentence", {s:"El vigilante nocturno estuvo trabajando en diferentes edificios a lo largo de la semana."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],
["practice", "DashedSentence", {s:"El cuarto de Raquel fue ocupados por un inquilino durante dos semanas."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],
["practice", "DashedSentence", {s:"El café fue molido por el camarero de una cafetería italiana."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],
["practice", "DashedSentence", {s:"Lola dio a Rita un ramo de flores el día de su aniversario."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],
["practice", "DashedSentence", {s:"El paciente dijeron a la cirujana que era alérgico a la anestesia."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],



["end_of_practice", "Message", {html: {include: "end_of_practice.html"}}],

[["first-second", 1], "DashedSentence", {s:"Queremos que vengáis a cenar."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 1], "DashedSentence", {s:"Queréis que vengáis a cenar."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 1], "DashedSentence", {s:"Queréis que vengamos a cenar."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 1], "DashedSentence", {s:"Queremos que vengamos a cenar."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 2], "DashedSentence", {s:"Deseamos que consigáis el premio."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 2], "DashedSentence", {s:"Deseáis que consigáis el premio."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 2], "DashedSentence", {s:"Deseáis que consigamos el premio."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 2], "DashedSentence", {s:"Deseamos que consigamos el premio."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 3], "DashedSentence", {s:"Preferimos que traigáis el postre."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 3], "DashedSentence", {s:"Preferís que traigáis el postre."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 3], "DashedSentence", {s:"Preferís que traigamos el postre."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 3], "DashedSentence", {s:"Preferimos que traigamos el postre."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 4], "DashedSentence", {s:"Agradecemos que presentéis una denuncia."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 4], "DashedSentence", {s:"Agradecéis que presentéis una denuncia."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 4], "DashedSentence", {s:"Agradecéis que presentemos una denuncia."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 4], "DashedSentence", {s:"Agradecemos que presentemos una denuncia."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 5], "DashedSentence", {s:"Necesitamos que compréis verdura fresca."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 5], "DashedSentence", {s:"Necesitáis que compréis verdura fresca."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 5], "DashedSentence", {s:"Necesitáis que compremos verdura fresca."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 5], "DashedSentence", {s:"Necesitamos que compremos verdura fresca."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 6], "DashedSentence", {s:"Sugerimos que vayáis a la tienda."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 6], "DashedSentence", {s:"Sugerís que vayáis a la tienda."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 6], "DashedSentence", {s:"Sugerís que vayamos a la tienda."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 6], "DashedSentence", {s:"Sugerimos que vayamos a la tienda."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 7], "DashedSentence", {s:"Pretendemos que aprobéis el examen."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 7], "DashedSentence", {s:"Pretendéis que aprobéis el examen."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 7], "DashedSentence", {s:"Pretendéis que aprobemos el examen."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 7], "DashedSentence", {s:"Pretendemos que aprobemos el examen."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 8], "DashedSentence", {s:"Odiamos que hagáis tantas travesuras."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 8], "DashedSentence", {s:"Odiáis que hagáis tantas travesuras."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 8], "DashedSentence", {s:"Odiáis que hagamos tantas travesuras."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 8], "DashedSentence", {s:"Odiamos que hagamos tantas travesuras."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 9], "DashedSentence", {s:"Recomendamos que tiréis la basura."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 9], "DashedSentence", {s:"Recomendáis que tiréis la basura."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 9], "DashedSentence", {s:"Recomendáis que tiremos la basura."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 9], "DashedSentence", {s:"Recomendamos que tiremos la basura."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 10], "DashedSentence", {s:"Ordenamos que entreguéis el examen."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 10], "DashedSentence", {s:"Ordenáis que entreguéis el examen."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 10], "DashedSentence", {s:"Ordenáis que entreguemos el examen."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 10], "DashedSentence", {s:"Ordenamos que entreguemos el examen."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 11], "DashedSentence", {s:"Queremos que consigáis la hipoteca."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 11], "DashedSentence", {s:"Queréis que consigáis la hipoteca."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 11], "DashedSentence", {s:"Queréis que consigamos la hipoteca."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 11], "DashedSentence", {s:"Queremos que consigamos la hipoteca."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 12], "DashedSentence", {s:"Deseamos que vengáis a la comida."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 12], "DashedSentence", {s:"Deseáis que vengáis a la comida."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 12], "DashedSentence", {s:"Deseáis que vengamos a la comida."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 12], "DashedSentence", {s:"Deseamos que vengamos a la comida."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 13], "DashedSentence", {s:"Preferimos que ganéis el partido."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 13], "DashedSentence", {s:"Preferís que ganéis el partido."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 13], "DashedSentence", {s:"Preferís que ganemos el partido."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 13], "DashedSentence", {s:"Preferimos que ganemos el partido."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 14], "DashedSentence", {s:"Agradecemos que respaldéis la candidatura."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 14], "DashedSentence", {s:"Agradecéis que respaldéis la candidatura."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 14], "DashedSentence", {s:"Agradecéis que respaldemos la candidatura."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 14], "DashedSentence", {s:"Agradecemos que respaldemos la candidatura."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 15], "DashedSentence", {s:"Necesitamos que apoyéis la iniciativa."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 15], "DashedSentence", {s:"Necesitáis que apoyéis la iniciativa."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 15], "DashedSentence", {s:"Necesitáis que apoyemos la iniciativa."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 15], "DashedSentence", {s:"Necesitamos que apoyemos la iniciativa."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 16], "DashedSentence", {s:"Sugerimos que convoquéis una reunión."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 16], "DashedSentence", {s:"Sugerís que convoquéis una reunión."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 16], "DashedSentence", {s:"Sugerís que convoquemos una reunión."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 16], "DashedSentence", {s:"Sugerimos que convoquemos una reunión."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 17], "DashedSentence", {s:"Pretendemos que denunciéis al hotel."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 17], "DashedSentence", {s:"Pretendéis que denunciéis al hotel."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 17], "DashedSentence", {s:"Pretendéis que denunciemos al hotel."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 17], "DashedSentence", {s:"Pretendemos que denunciemos al hotel."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 18], "DashedSentence", {s:"Odiamos que lleguéis tan tarde."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 18], "DashedSentence", {s:"Odiáis que lleguéis tan tarde."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 18], "DashedSentence", {s:"Odiáis que lleguemos tan tarde."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 18], "DashedSentence", {s:"Odiamos que lleguemos tan tarde."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 19], "DashedSentence", {s:"Recomendamos que mantengáis la calma."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 19], "DashedSentence", {s:"Recomendáis que mantengáis la calma."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 19], "DashedSentence", {s:"Recomendáis que mantengamos la calma."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 19], "DashedSentence", {s:"Recomendamos que mantengamos la calma."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 20], "DashedSentence", {s:"Ordenamos que asistáis a la asamblea."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 20], "DashedSentence", {s:"Ordenáis que asistáis a la asamblea."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 20], "DashedSentence", {s:"Ordenáis que asistamos a la asamblea."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 20], "DashedSentence", {s:"Ordenamos que asistamos a la asamblea."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 21], "DashedSentence", {s:"Queremos que acudáis a la fiesta."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 21], "DashedSentence", {s:"Queréis que acudáis a la fiesta."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 21], "DashedSentence", {s:"Queréis que acudamos a la fiesta."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 21], "DashedSentence", {s:"Queremos que acudamos a la fiesta."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 22], "DashedSentence", {s:"Deseamos que tengáis mucho éxito."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 22], "DashedSentence", {s:"Deseáis que tengáis mucho éxito."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 22], "DashedSentence", {s:"Deseáis que tengamos mucho éxito."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 22], "DashedSentence", {s:"Deseamos que tengamos mucho éxito."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 23], "DashedSentence", {s:"Preferimos que escojáis el restaurante."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 23], "DashedSentence", {s:"Preferís que escojáis el restaurante."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 23], "DashedSentence", {s:"Preferís que escojamos el restaurante."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 23], "DashedSentence", {s:"Preferimos que escojamos el restaurante."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 24], "DashedSentence", {s:"Agradecemos que apoyéis esta causa."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 24], "DashedSentence", {s:"Agradecéis que apoyéis esta causa."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 24], "DashedSentence", {s:"Agradecéis que apoyemos esta causa."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 24], "DashedSentence", {s:"Agradecemos que apoyemos esta causa."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 25], "DashedSentence", {s:"Necesitamos que tengáis mucho cuidado."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 25], "DashedSentence", {s:"Necesitáis que tengáis mucho cuidado."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 25], "DashedSentence", {s:"Necesitáis que tengamos mucho cuidado."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 25], "DashedSentence", {s:"Necesitamos que tengamos mucho cuidado."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 26], "DashedSentence", {s:"Sugerimos que limpiéis el piso."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 26], "DashedSentence", {s:"Sugerís que limpiéis el piso."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 26], "DashedSentence", {s:"Sugerís que limpiemos el piso."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 26], "DashedSentence", {s:"Sugerimos que limpiemos el piso."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 27], "DashedSentence", {s:"Pretendemos que tengáis más vacaciones."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 27], "DashedSentence", {s:"Pretendéis que tengáis más vacaciones."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 27], "DashedSentence", {s:"Pretendéis que tengamos más vacaciones."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 27], "DashedSentence", {s:"Pretendemos que tengamos más vacaciones."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 28], "DashedSentence", {s:"Odiamos que habléis sin permiso."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 28], "DashedSentence", {s:"Odiáis que habléis sin permiso."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 28], "DashedSentence", {s:"Odiáis que hablemos sin permiso."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 28], "DashedSentence", {s:"Odiamos que hablemos sin permiso."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 29], "DashedSentence", {s:"Recomendamos que prestéis más atención."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 29], "DashedSentence", {s:"Recomendáis que prestéis más atención."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 29], "DashedSentence", {s:"Recomendáis que prestemos más atención."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 29], "DashedSentence", {s:"Recomendamos que prestemos más atención."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 30], "DashedSentence", {s:"Ordenamos que apaguéis la música."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 30], "DashedSentence", {s:"Ordenáis que apaguéis la música."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 30], "DashedSentence", {s:"Ordenáis que apaguemos la música."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 30], "DashedSentence", {s:"Ordenamos que apaguemos la música."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 31], "DashedSentence", {s:"Queremos que ganéis la carrera."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 31], "DashedSentence", {s:"Queréis que ganéis la carrera."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 31], "DashedSentence", {s:"Queréis que ganemos la carrera."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 31], "DashedSentence", {s:"Queremos que ganemos la carrera."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 32], "DashedSentence", {s:"Deseamos que asistáis a la ceremonia."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 32], "DashedSentence", {s:"Deseáis que asistáis a la ceremonia."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 32], "DashedSentence", {s:"Deseáis que asistamos a la ceremonia."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 32], "DashedSentence", {s:"Deseamos que asistamos a la ceremonia."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 33], "DashedSentence", {s:"Preferimos que compréis vino tinto."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 33], "DashedSentence", {s:"Preferís que compréis vino tinto."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 33], "DashedSentence", {s:"Preferís que compremos vino tinto."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 33], "DashedSentence", {s:"Preferimos que compremos vino tinto."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 34], "DashedSentence", {s:"Agradecemos que secundéis la huelga."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 34], "DashedSentence", {s:"Agradecéis que secundéis la huelga."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 34], "DashedSentence", {s:"Agradecéis que secundemos la huelga."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 34], "DashedSentence", {s:"Agradecemos que secundemos la huelga."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 35], "DashedSentence", {s:"Necesitamos que terminéis las obras."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 35], "DashedSentence", {s:"Necesitáis que terminéis las obras."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 35], "DashedSentence", {s:"Necesitáis que terminemos las obras."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 35], "DashedSentence", {s:"Necesitamos que terminemos las obras."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 36], "DashedSentence", {s:"Sugerimos que tengáis más productos."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 36], "DashedSentence", {s:"Sugerís que tengáis más productos."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 36], "DashedSentence", {s:"Sugerís que tengamos más productos."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 36], "DashedSentence", {s:"Sugerimos que tengamos más productos."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 37], "DashedSentence", {s:"Pretendemos que hagáis las paces."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 37], "DashedSentence", {s:"Pretendéis que hagáis las paces."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 37], "DashedSentence", {s:"Pretendéis que hagamos las paces."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 37], "DashedSentence", {s:"Pretendemos que hagamos las paces."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 38], "DashedSentence", {s:"Odiamos que seáis unos irresponsables."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 38], "DashedSentence", {s:"Odiáis que seáis unos irresponsables."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 38], "DashedSentence", {s:"Odiáis que seamos unos irresponsables."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 38], "DashedSentence", {s:"Odiamos que seamos unos irresponsables."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 39], "DashedSentence", {s:"Recomendamos que asistáis a la charla."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 39], "DashedSentence", {s:"Recomendáis que asistáis a la charla."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 39], "DashedSentence", {s:"Recomendáis que asistamos a la charla."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 39], "DashedSentence", {s:"Recomendamos que asistamos a la charla."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-second", 40], "DashedSentence", {s:"Ordenamos que solucionéis el problema."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-second", 40], "DashedSentence", {s:"Ordenáis que solucionéis el problema."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["second-first", 40], "DashedSentence", {s:"Ordenáis que solucionemos el problema."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["first-first", 40], "DashedSentence", {s:"Ordenamos que solucionemos el problema."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],


[["subj-subj", 41], "DashedSentence", {s:"Que imprima en papel blanco reciclado es lo que Fernando le ha aconsejado a María."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 41], "DashedSentence", {s:"Que imprime en papel blanco reciclado es lo que Fernando le ha aconsejado a María."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 41], "DashedSentence", {s:"Que imprima en papel blanco reciclado es lo que Fernando le ha garantizado a María."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 41], "DashedSentence", {s:"Que imprime en papel blanco reciclado es lo que Fernando le ha garantizado a María."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 42], "DashedSentence", {s:"Que cambie las sábanas los lunes es lo que Marta le ha ordenado a Lucas."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 42], "DashedSentence", {s:"Que cambia las sábanas los lunes es lo que Marta le ha ordenado a Lucas."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 42], "DashedSentence", {s:"Que cambie las sábanas los lunes es lo que Marta le ha jurado a Lucas."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 42], "DashedSentence", {s:"Que cambia las sábanas los lunes es lo que Marta le ha jurado a Lucas."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 43], "DashedSentence", {s:"Que tome pastillas contra la ansiedad es lo que Carlos le ha recomendado a Laura."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 43], "DashedSentence", {s:"Que toma pastillas contra la ansiedad es lo que Carlos le ha recomendado a Laura."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 43], "DashedSentence", {s:"Que tome pastillas contra la ansiedad es lo que Carlos le ha confesado a Laura."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 43], "DashedSentence", {s:"Que toma pastillas contra la ansiedad es lo que Carlos le ha confesado a Laura."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 44], "DashedSentence", {s:"Que abandone la dirección del partido es lo que Patricia le ha sugerido a Antonio."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 44], "DashedSentence", {s:"Que abandona la dirección del partido es lo que Patricia le ha sugerido a Antonio."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 44], "DashedSentence", {s:"Que abandone la dirección del partido es lo que Patricia le ha asegurado a Antonio."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 44], "DashedSentence", {s:"Que abandona la dirección del partido es lo que Patricia le ha asegurado a Antonio."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 45], "DashedSentence", {s:"Que coja el coche del comercial es lo que Juan le ha permitido a Olga."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 45], "DashedSentence", {s:"Que coge el coche del comercial es lo que Juan le ha permitido a Olga."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 45], "DashedSentence", {s:"Que coja el coche del comercial es lo que Juan le ha contado a Olga."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 45], "DashedSentence", {s:"Que coge el coche del comercial es lo que Juan le ha contado a Olga."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 46], "DashedSentence", {s:"Que apoye la propuesta del sindicato es lo que Silvia le ha exigido a Nicolás."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 46], "DashedSentence", {s:"Que apoya la propuesta del sindicato es lo que Silvia le ha exigido a Nicolás."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 46], "DashedSentence", {s:"Que apoye la propuesta del sindicato es lo que Silvia le ha declarado a Nicolás."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 46], "DashedSentence", {s:"Que apoya la propuesta del sindicato es lo que Silvia le ha declarado a Nicolás."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 47], "DashedSentence", {s:"Que apueste en carreras de galgos es lo que Oscar le ha prohibido a Rosa."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 47], "DashedSentence", {s:"Que apuesta en carreras de galgos es lo que Oscar le ha prohibido a Rosa."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 47], "DashedSentence", {s:"Que apueste en carreras de galgos es lo que Oscar le ha manifestado a Rosa."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 47], "DashedSentence", {s:"Que apuesta en carreras de galgos es lo que Oscar le ha manifestado a Rosa."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 48], "DashedSentence", {s:"Que utilice unos guantes de jardinería es lo que Vanesa le ha mandado a Ramón."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 48], "DashedSentence", {s:"Que utiliza unos guantes de jardinería es lo que Vanesa le ha mandado a Ramón."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 48], "DashedSentence", {s:"Que utilice unos guantes de jardinería es lo que Vanesa le ha mostrado a Ramón."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 48], "DashedSentence", {s:"Que utiliza unos guantes de jardinería es lo que Vanesa le ha mostrado a Ramón."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 49], "DashedSentence", {s:"Que tienda las camisas de vestir es lo que Pilar le ha aconsejado a Rafael."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 49], "DashedSentence", {s:"Que tiende las camisas de vestir es lo que Pilar le ha aconsejado a Rafael."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 49], "DashedSentence", {s:"Que tienda las camisas de vestir es lo que Pilar le ha garantizado a Rafael."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 49], "DashedSentence", {s:"Que tiende las camisas de vestir es lo que Pilar le ha garantizado a Rafael."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 50], "DashedSentence", {s:"Que revise el correo a diario es lo que Daniel le ha ordenado a Mónica."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 50], "DashedSentence", {s:"Que revisa el correo a diario es lo que Daniel le ha ordenado a Mónica."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 50], "DashedSentence", {s:"Que revise el correo a diario es lo que Daniel le ha jurado a Mónica."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 50], "DashedSentence", {s:"Que revisa el correo a diario es lo que Daniel le ha jurado a Mónica."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 51], "DashedSentence", {s:"Que guarde una pistola en casa es lo que Carmen le ha recomendado a Jorge."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 51], "DashedSentence", {s:"Que guarda una pistola en casa es lo que Carmen le ha recomendado a Jorge."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 51], "DashedSentence", {s:"Que guarde una pistola en casa es lo que Carmen le ha confesado a Jorge."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 51], "DashedSentence", {s:"Que guarda una pistola en casa es lo que Carmen le ha confesado a Jorge."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 52], "DashedSentence", {s:"Que compre el pescado en Tarragona es lo que José le ha sugerido a Teresa."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 52], "DashedSentence", {s:"Que compra el pescado en Tarragona es lo que José le ha sugerido a Teresa."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 52], "DashedSentence", {s:"Que compre el pescado en Tarragona es lo que José le ha asegurado a Teresa."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 52], "DashedSentence", {s:"Que compra el pescado en Tarragona es lo que José le ha asegurado a Teresa."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 53], "DashedSentence", {s:"Que guarde los esquís en casa es lo que Natalia le ha permitido a Alberto."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 53], "DashedSentence", {s:"Que guarda los esquís en casa es lo que Natalia le ha permitido a Alberto."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 53], "DashedSentence", {s:"Que guarde los esquís en casa es lo que Natalia le ha contado a Alberto."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 53], "DashedSentence", {s:"Que guarda los esquís en casa es lo que Natalia le ha contado a Alberto."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 54], "DashedSentence", {s:"Que tenga dinero en el banco es lo que Alfonso le ha exigido a Alicia."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 54], "DashedSentence", {s:"Que tiene dinero en el banco es lo que Alfonso le ha exigido a Alicia."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 54], "DashedSentence", {s:"Que tenga dinero en el banco es lo que Alfonso le ha declarado a Alicia."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 54], "DashedSentence", {s:"Que tiene dinero en el banco es lo que Alfonso le ha declarado a Alicia."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 55], "DashedSentence", {s:"Que escuche música por la noche es lo que Mercedes le ha prohibido a Ricardo."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 55], "DashedSentence", {s:"Que escucha música por la noche es lo que Mercedes le ha prohibido a Ricardo."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 55], "DashedSentence", {s:"Que escuche música por la noche es lo que Mercedes le ha manifestado a Ricardo."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 55], "DashedSentence", {s:"Que escucha música por la noche es lo que Mercedes le ha manifestado a Ricardo."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 56], "DashedSentence", {s:"Que tenga una póliza contra incendios es lo que Roberto le ha mandado a Ana."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 56], "DashedSentence", {s:"Que tiene una póliza contra incendios es lo que Roberto le ha mandado a Ana."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 56], "DashedSentence", {s:"Que tenga una póliza contra incendios es lo que Roberto le ha mostrado a Ana."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 56], "DashedSentence", {s:"Que tiene una póliza contra incendios es lo que Roberto le ha mostrado a Ana."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 57], "DashedSentence", {s:"Que lleve bebidas para la fiesta es lo que Miguel le ha aconsejado a Sara."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 57], "DashedSentence", {s:"Que lleva bebidas para la fiesta es lo que Miguel le ha aconsejado a Sara."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 57], "DashedSentence", {s:"Que lleve bebidas para la fiesta es lo que Miguel le ha garantizado a Sara."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 57], "DashedSentence", {s:"Que lleva bebidas para la fiesta es lo que Miguel le ha garantizado a Sara."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 58], "DashedSentence", {s:"Que haga la cama cada mañana es lo que Ester le ha ordenado a Andrés."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 58], "DashedSentence", {s:"Que hace la cama cada mañana es lo que Ester le ha ordenado a Andrés."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 58], "DashedSentence", {s:"Que haga la cama cada mañana es lo que Ester le ha jurado a Andrés."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 58], "DashedSentence", {s:"Que hace la cama cada mañana es lo que Ester le ha jurado a Andrés."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 59], "DashedSentence", {s:"Que fume en el jardín privado es lo que Ignacio le ha recomendado a Elena."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 59], "DashedSentence", {s:"Que fuma en el jardín privado es lo que Ignacio le ha recomendado a Elena."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 59], "DashedSentence", {s:"Que fume en el jardín privado es lo que Ignacio le ha confesado a Elena."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 59], "DashedSentence", {s:"Que fuma en el jardín privado es lo que Ignacio le ha confesado a Elena."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 60], "DashedSentence", {s:"Que lea la columna del filósofo es lo que Susana le ha sugerido a Enrique."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 60], "DashedSentence", {s:"Que lee la columna del filósofo es lo que Susana le ha sugerido a Enrique."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 60], "DashedSentence", {s:"Que lea la columna del filósofo es lo que Susana le ha asegurado a Enrique."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 60], "DashedSentence", {s:"Que lee la columna del filósofo es lo que Susana le ha asegurado a Enrique."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 61], "DashedSentence", {s:"Que entrene con el equipo profesional es lo que Javier le ha permitido a Adriana."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 61], "DashedSentence", {s:"Que entrena con el equipo profesional es lo que Javier le ha permitido a Adriana."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 61], "DashedSentence", {s:"Que entrene con el equipo profesional es lo que Javier le ha contado a Adriana."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 61], "DashedSentence", {s:"Que entrena con el equipo profesional es lo que Javier le ha contado a Adriana."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 62], "DashedSentence", {s:"Que cambie el tipo de contrato es lo que Inés le ha exigido a Diego."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 62], "DashedSentence", {s:"Que cambia el tipo de contrato es lo que Inés le ha exigido a Diego."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 62], "DashedSentence", {s:"Que cambie el tipo de contrato es lo que Inés le ha declarado a Diego."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 62], "DashedSentence", {s:"Que cambia el tipo de contrato es lo que Inés le ha declarado a Diego."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 63], "DashedSentence", {s:"Que espíe a los nuevos vecinos es lo que Raúl le ha prohibido a Isabel."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 63], "DashedSentence", {s:"Que espía a los nuevos vecinos es lo que Raúl le ha prohibido a Isabel."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 63], "DashedSentence", {s:"Que espíe a los nuevos vecinos es lo que Raúl le ha manifestado a Isabel."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 63], "DashedSentence", {s:"Que espía a los nuevos vecinos es lo que Raúl le ha manifestado a Isabel."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 64], "DashedSentence", {s:"Que deje el coche con gasolina es lo que Cecilia le ha mandado a Eduardo."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 64], "DashedSentence", {s:"Que deja el coche con gasolina es lo que Cecilia le ha mandado a Eduardo."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 64], "DashedSentence", {s:"Que deje el coche con gasolina es lo que Cecilia le ha mostrado a Eduardo."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 64], "DashedSentence", {s:"Que deja el coche con gasolina es lo que Cecilia le ha mostrado a Eduardo."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 65], "DashedSentence", {s:"Que riegue los rosales del patio es lo que Elisa le ha aconsejado a Héctor."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 65], "DashedSentence", {s:"Que riega los rosales del patio es lo que Elisa le ha aconsejado a Héctor."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 65], "DashedSentence", {s:"Que riegue los rosales del patio es lo que Elisa le ha garantizado a Héctor."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 65], "DashedSentence", {s:"Que riega los rosales del patio es lo que Elisa le ha garantizado a Héctor."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 66], "DashedSentence", {s:"Que cierre la puerta con llave es lo que Mario le ha ordenado a Sofía."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 66], "DashedSentence", {s:"Que cierra la puerta con llave es lo que Mario le ha ordenado a Sofía."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 66], "DashedSentence", {s:"Que cierre la puerta con llave es lo que Mario le ha jurado a Sofía."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 66], "DashedSentence", {s:"Que cierra la puerta con llave es lo que Mario le ha jurado a Sofía."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 67], "DashedSentence", {s:"Que lea los libros del poeta es lo que Carlota le ha recomendado a Joaquín."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 67], "DashedSentence", {s:"Que lee los libros del poeta es lo que Carlota le ha recomendado a Joaquín."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 67], "DashedSentence", {s:"Que lea los libros del poeta es lo que Carlota le ha confesado a Joaquín."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 67], "DashedSentence", {s:"Que lee los libros del poeta es lo que Carlota le ha confesado a Joaquín."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 68], "DashedSentence", {s:"Que coma las hamburguesas sin kétchup es lo que Guillermo le ha sugerido a Luisa."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 68], "DashedSentence", {s:"Que come las hamburguesas sin kétchup es lo que Guillermo le ha sugerido a Luisa."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 68], "DashedSentence", {s:"Que coma las hamburguesas sin kétchup es lo que Guillermo le ha asegurado a Luisa."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 68], "DashedSentence", {s:"Que come las hamburguesas sin kétchup es lo que Guillermo le ha asegurado a Luisa."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 69], "DashedSentence", {s:"Que trabaje desde su propia casa es lo que Celia le ha permitido a Víctor."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 69], "DashedSentence", {s:"Que trabaja desde su propia casa es lo que Celia le ha permitido a Víctor."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 69], "DashedSentence", {s:"Que trabaje desde su propia casa es lo que Celia le ha contado a Víctor."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 69], "DashedSentence", {s:"Que trabaja desde su propia casa es lo que Celia le ha contado a Víctor."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 70], "DashedSentence", {s:"Que haga los ejercicios cada día es lo que Felipe le ha exigido a Irene."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 70], "DashedSentence", {s:"Que hace los ejercicios cada día es lo que Felipe le ha exigido a Irene."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 70], "DashedSentence", {s:"Que haga los ejercicios cada día es lo que Felipe le ha declarado a Irene."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 70], "DashedSentence", {s:"Que hace los ejercicios cada día es lo que Felipe le ha declarado a Irene."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 71], "DashedSentence", {s:"Que duerma en el sofá cama es lo que Eva le ha prohibido a Jaime."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 71], "DashedSentence", {s:"Que duerme en el sofá cama es lo que Eva le ha prohibido a Jaime."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 71], "DashedSentence", {s:"Que duerma en el sofá cama es lo que Eva le ha manifestado a Jaime."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 71], "DashedSentence", {s:"Que duerme en el sofá cama es lo que Eva le ha manifestado a Jaime."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 72], "DashedSentence", {s:"Que planche la ropa de verano es lo que Martín le ha mandado a Cristina."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 72], "DashedSentence", {s:"Que plancha la ropa de verano es lo que Martín le ha mandado a Cristina."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 72], "DashedSentence", {s:"Que planche la ropa de verano es lo que Martín le ha mostrado a Cristina."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 72], "DashedSentence", {s:"Que plancha la ropa de verano es lo que Martín le ha mostrado a Cristina."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 73], "DashedSentence", {s:"Que corra una hora al día es lo que Álvaro le ha aconsejado a Paula."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 73], "DashedSentence", {s:"Que corre una hora al día es lo que Álvaro le ha aconsejado a Paula."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 73], "DashedSentence", {s:"Que corra una hora al día es lo que Álvaro le ha garantizado a Paula."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 73], "DashedSentence", {s:"Que corre una hora al día es lo que Álvaro le ha garantizado a Paula."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 74], "DashedSentence", {s:"Que respete los límites de velocidad es lo que Verónica le ha ordenado a Emilio."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 74], "DashedSentence", {s:"Que respeta los límites de velocidad es lo que Verónica le ha ordenado a Emilio."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 74], "DashedSentence", {s:"Que respete los límites de velocidad es lo que Verónica le ha jurado a Emilio."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 74], "DashedSentence", {s:"Que respeta los límites de velocidad es lo que Verónica le ha jurado a Emilio."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 75], "DashedSentence", {s:"Que siga la dieta del nutricionista es lo que Julio le ha recomendado a Claudia."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 75], "DashedSentence", {s:"Que sigue la dieta del nutricionista es lo que Julio le ha recomendado a Claudia."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 75], "DashedSentence", {s:"Que siga la dieta del nutricionista es lo que Julio le ha confesado a Claudia."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 75], "DashedSentence", {s:"Que sigue la dieta del nutricionista es lo que Julio le ha confesado a Claudia."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 76], "DashedSentence", {s:"Que use el nuevo patinete eléctrico es lo que Lourdes le ha sugerido a Marcos."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 76], "DashedSentence", {s:"Que usa el nuevo patinete eléctrico es lo que Lourdes le ha sugerido a Marcos."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 76], "DashedSentence", {s:"Que use el nuevo patinete eléctrico es lo que Lourdes le ha asegurado a Marcos."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 76], "DashedSentence", {s:"Que usa el nuevo patinete eléctrico es lo que Lourdes le ha asegurado a Marcos."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 77], "DashedSentence", {s:"Que comparta despacho con un amigo es lo que Vicente le ha permitido a Margarita."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 77], "DashedSentence", {s:"Que comparte despacho con un amigo es lo que Vicente le ha permitido a Margarita."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 77], "DashedSentence", {s:"Que comparta despacho con un amigo es lo que Vicente le ha contado a Margarita"},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 77], "DashedSentence", {s:"Que comparte despacho con un amigo es lo que Vicente le ha contado a Margarita."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 78], "DashedSentence", {s:"Que prepare los trámites del divorcio es lo que Lidia le ha exigido a Sergio."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 78], "DashedSentence", {s:"Que prepara los trámites del divorcio es lo que Lidia le ha exigido a Sergio."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 78], "DashedSentence", {s:"Que prepare los trámites del divorcio es lo que Lidia le ha declarado a Sergio."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 78], "DashedSentence", {s:"Que prepara los trámites del divorcio es lo que Lidia le ha declarado a Sergio."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 79], "DashedSentence", {s:"Que consuma a diario bebidas estimulantes es lo que Armando le ha prohibido a Gloria."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 79], "DashedSentence", {s:"Que consume a diario bebidas estimulantes es lo que Armando le ha prohibido a Gloria."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 79], "DashedSentence", {s:"Que consuma a diario bebidas estimulantes es lo que Armando le ha manifestado a Gloria."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 79], "DashedSentence", {s:"Que consume a diario bebidas estimulantes es lo que Armando le ha manifestado a Gloria."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-subj", 80], "DashedSentence", {s:"Que corte el césped del jardín es lo que Sonia le ha mandado a Manuel."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["subj-indi", 80], "DashedSentence", {s:"Que corta el césped del jardín es lo que Sonia le ha mandado a Manuel."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-subj", 80], "DashedSentence", {s:"Que corte el césped del jardín es lo que Sonia le ha mostrado a Manuel."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],
[["indi-indi", 80], "DashedSentence", {s:"Que corta el césped del jardín es lo que Sonia le ha mostrado a Manuel."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:false}],


["filler_ug", "DashedSentence", {s:"El joven aprendiz fueron humillado por el alto ejecutivo."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],
["filler_gr", "DashedSentence", {s:"El reputado novelista aceptó que lo entrevistaran los alumnos de tercero."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],
["filler_ug", "DashedSentence", {s:"José fue corregida por el asistente."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],
["filler_gr", "DashedSentence", {s:"Carmen se dejó engañar por el amigo del estafador."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],
["filler_ug", "DashedSentence", {s:"Carlos llamó al candidato que fueron condenados por el experimentado juez."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],
["filler_gr", "DashedSentence", {s:"La encantadora mujer fue asustada por el gato negro."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],
["filler_ug", "DashedSentence", {s:"El diputado fue golpeado por el  senador conservadora."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],
["filler_gr", "DashedSentence", {s:"Pedro nos dijo que el viaje fue cancelado por el guía debido a las numerosas bajas."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],
["filler_ug", "DashedSentence", {s:"El hombre mayor fue ayudado por el educada vecino."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],
["filler_gr", "DashedSentence", {s:"El bailarín alto fue recomendado por la prometedora actriz."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],
["filler_ug", "DashedSentence", {s:"El novio recibieron un gran paquete como regalo de parte de su novia."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],
["filler_gr", "DashedSentence", {s:"El resultado de las elecciones fue notificado por el portavoz del partido."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],
["filler_ug", "DashedSentence", {s:"El ladrón de cuadros fue observada por el detective."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],
["filler_gr", "DashedSentence", {s:"Pedro compartió en las redes lo que le había enviado el crítico del programa para su cumpleaños."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],
["filler_ug", "DashedSentence", {s:"Marisa mostramos la carta que le escribió a la abuela de Rosalía."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],
["filler_gr", "DashedSentence", {s:"La hija del futbolista salió de paseo con el coche de su padre."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],
["filler_ug", "DashedSentence", {s:"El marido de Sonia acaban de salir de la consulta."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],
["filler_gr", "DashedSentence", {s:"La amiga del director de cine estuvo ayer en el plató."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],
["filler_ug", "DashedSentence", {s:"El amigo del alcalde va cada fines de semana a nadar eufórico al mar."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],
["filler_gr", "DashedSentence", {s:"La chef del empresario cocinaba una tortilla de patatas."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],
["filler_ug", "DashedSentence", {s:"El jardinero podaremos cuidadoso los gladiolos de los jardines del palacio."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],
["filler_gr", "DashedSentence", {s:"La modista estaba visitando el pueblo por primera vez."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],
["filler_ug", "DashedSentence", {s:"El fisioterapeuta de la futbolista estabais en el partido cuando marcó un gol."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],
["filler_gr", "DashedSentence", {s:"La esposa del entrenador tomaba el sol en la playa."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],
["filler_ug", "DashedSentence", {s:"El novio de la ciclista fue vistos cerca del conservatorio."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],
["filler_gr", "DashedSentence", {s:"El maestro de mi vecino trabajó de joven en el bar de la estación."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],
["filler_ug", "DashedSentence", {s:"A Conchita le sorprendió lo bien que hablaban el español la amiga de Susan."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],
["filler_gr", "DashedSentence", {s:"El veterinario de mi perro sale a hacer jogging cada día por el parque."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],
["filler_ug", "DashedSentence", {s:"Marina me dijo que su prima se graduaron en Barcelona."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],
["filler_gr", "DashedSentence", {s:"El maestro viajó a Moscú cuando tenía veinte años."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],
["filler_ug", "DashedSentence", {s:"María diseñó un nuevo programa para disminuir el niveles de contaminación."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],
["filler_gr", "DashedSentence", {s:"Marta tuvo claro desde pequeña que quería ser nadadora y se entrenaba diariamente."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],
["filler_ug", "DashedSentence", {s:"Patricia abrió su propio negocio de vinilos e instrumentos musical en Lisboa."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],
["filler_gr", "DashedSentence", {s:"Fernando recorre el mundo en bicicleta para denunciar el cambio climático."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],
["filler_ug", "DashedSentence", {s:"La maestra de la escuela de primaria vimos a Pedro corriendo por el patio."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],
["filler_gr", "DashedSentence", {s:"El enfermero pilló a Ana cuando intentaba escaparse del hospital."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],
["filler_ug", "DashedSentence", {s:"Javier saludó a Laura que iban apurados a tomar el tren."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],
["filler_gr", "DashedSentence", {s:"El técnico del laboratorio observó que Rosa estaba teniendo problemas con el proyector."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],
["filler_ug", "DashedSentence", {s:"El presentador invite a Carmen a un concierto de flamenco."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:1}],
["filler_gr", "DashedSentence", {s:"Marta grababa a Cristina mientras esta hacía piruetas con el monopatín."},"Question", {q: "¿Te ha parecido correcta esta oración?", hasCorrect:0}],


["participant_observations", "Form", {html: {include: "participant_observations.html"}}]



];
